---
name: Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  TWITCH_PUBSUB_SERVER_IMAGE: ghcr.io/chatterino/twitch-pubsub-server-test:v1.0.6

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go:
          - "1.19"
          - "1.20"
        os:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "macos-latest"

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v4

      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...

      - name: Build example
        run: go build
        working-directory: cmd/example

      - name: Test
        run: |
          docker pull ${{ env.TWITCH_PUBSUB_SERVER_IMAGE }}
          docker run --network=host --detach ${{ env.TWITCH_PUBSUB_SERVER_IMAGE }}
          go test -v ./...

      - name: Generate code coverage
        if: matrix.os == 'ubuntu-22.04' && matrix.go == '1.19'
        run: go test -race -v -count=1 -coverprofile=coverage.out ./...

      - name: Upload Test Coverage
        if: matrix.os == 'ubuntu-22.04' && matrix.go == '1.19'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chatterino-api-${{ matrix.go }}-${{ matrix.os }}
          path: build/chatterino-api
